version 1
dev-Orlov/java-filmorate pull request #1
Opened 2022-10-07 21:13 UTC by dev-Orlov

2022-10-08 13:15 UTC, andrew-larkin requested changes
Привет! Отличный результат, нужно немного отрефакторить в паре мест и работа будет принята.

2022-10-08 13:15 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private HashMap<Integer, Film> films = new HashMap<>();
стоит добавить ключевое слово final, чтобы при инициализации приложения ссылку на эту коллекцию уже нельзя было изменить

2022-10-08 13:15 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        List<Film> filmsList = new ArrayList<>();
нам пока что необязательно создавать доп.коллекции, достаточно просто возвращать значения хэшмапы:
return new ArrayList<>(films.values());

2022-10-08 13:15 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
в этом контроллере аналогичные правки как и в FilmController

2022-10-08 13:15 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/validator/FilmValidatorTest.java
> +        Film film1 = Film.builder()
чтобы не создавать в каждом тесте отдельный фильм, можно вынести его создание в отдельный метод, в котором будет создан "хороший" фильм. Затем в каждом тесте достаточно вызывать этот метод и с помощью сеттера или билдера устанавливать "неправильное" поле, на которое и будет направлена проверка в каждом отдельном случае

2022-10-09 08:49 UTC, dev-Orlov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private HashMap<Integer, Film> films = new HashMap<>();
✅

2022-10-09 08:51 UTC, dev-Orlov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        List<Film> filmsList = new ArrayList<>();
✅

2022-10-09 08:52 UTC, dev-Orlov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
✅

2022-10-09 09:07 UTC, dev-Orlov commented on src/test/java/ru/yandex/practicum/filmorate/validator/FilmValidatorTest.java
> +        Film film1 = Film.builder()
✅

2022-10-09 17:24 UTC, merged