Add database
dev-Orlov/java-filmorate pull request #6
Opened 2022-11-30 23:57 UTC by dev-Orlov

2022-12-01 18:47 UTC, andrew-larkin requested changes
Привет! Отлично сделано, не к чему придраться. Есть всего одно предложение по контроллерам, но если не успеваешь, но можно не делать.

2022-12-01 18:47 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public List<Film> getPopularFilms(@RequestParam(required = false) Integer count) {
в реальных проектах ответы контроллера оборачиваются в класс ResponseEntity - он возвращает не только json, но и http-статус, что очень удобно.

2022-12-02 12:56 UTC, dev-Orlov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public List<Film> getPopularFilms(@RequestParam(required = false) Integer count) {
Пока читал о ResponseEntity  наткнулся на статью, в которой было сказано, что оборачивать ответы контроллера в ResponseEntity - это моветон. Что фронту будет не очень понятно, что происходит. Поэтому сделал GlobalExceptionHandler, в котором уже есть работа с ResponseEntity. А методы контроллера возвращают те же объекты в нужном виде.

2022-12-02 12:59 UTC, dev-Orlov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public List<Film> getPopularFilms(@RequestParam(required = false) Integer count) {
upd
я поправил и вижу изменения в ветке, но в пулл реквесте почему-то последний коммит не отобразился. Если я что-то не так сделал с гитом - подскажи, пожалуйста. Пока не соображу, должно ли быть так

2022-12-04 08:16 UTC, merged